### PR TITLE
Custom VZbot VZ-Printhead mount

### PR DESCRIPTION
**Pull request by esc247**
I've created a custom mount for the Euclid Probe for the VZ-Printhead. (Euclid mount VZ-printhead v5)

It needs to be assembled onto the 5015 fan at the back.

The dock that I used is the VoronGantyMountRev_4 filed down a little bit along with the RailCoreTopMountLong, assembled the other way to make the Mount fit.

The image should make the assembly clearer.

I've added the docks from the other repos here to make it easier to find the full assembly.

### CODE REVIEW

**Comment by nionio6915** [comment]
can you email me or DM on Discord? 
I need help merging this.

**Comment by esc247** [comment]
Hi, sorry for the late reply. I do not have access to the croxy discord anymore as my account had issues and it started spamming….and then I got banned. Not sure how to get access back to the server again. Seems like you have merged this now though. Thanks!

**Comment by nionio6915** [comment]
iam sorry to hear about your discord issues. yes, spammers got banned from the croxy. 
what was your handle? i will try to get it reinstated for you.
i did finally figure it out. 
thanks for your contribution

**Comment by esc247** [comment]
Sorted the issue out. My handle is esc247. Thanks for all of your contribution, much rather :)

**Pull request merged**
